<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\AppIcon.ico" />
    <None Remove="Assets\AppIcon.png" />
    <Resource Include="Assets\AppIcon.ico" />
    <Resource Include="Assets\AppIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.13.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
  </ItemGroup>
</Project>
